name: CD workflow on dev/prod branch
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: install docker
        uses: docker-practice/actions-setup-docker@master

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: create docker-image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:img2 .

      - name: push code
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:img2


