name: CD
on:
  push:
    branches:
      - dev

  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: install docker
        uses: docker-practice/actions-setup-docker@master

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: create image
        run: | 
          if ${{ github.ref_name != 'dev' && github.event_name == 'workflow_dispatch' }}
          then
            echo "Workflow dispatch is only allowed on dev branch."
            exit 1
          fi
          
          if ${{ github.ref_name == 'dev' }}
          then
            docker build -t ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }} .
          else
            docker build -t ${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }} .
          fi

      - name: push image
        run: |
          if ${{ github.ref_name == 'dev' }}
          then
            docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
          else
            docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }}
          fi

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: build
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Deploy image to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ${{ github.ref_name == 'dev' }}
            then
              docker pull ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
              docker run -d -e APP_AWS_REGION_NAME='ca-central-1' -p 80:5000 ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
            else
              docker pull ${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }}
              docker run -d -e APP_AWS_REGION_NAME='ca-central-1' -p 80:5000 ${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }}
            fi

  healthcheck:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: deploy
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: http://${{ secrets.SSH_HOST }}/health
          follow-redirect: true # Optional, defaults to false
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
