name: CI

on:
  pull_request:
    branches:
      - dev
      - prod

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run flake8
        run: |
          flake8

  unit-testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-md

      - name: install Docker
        uses: docker-practice/actions-setup-docker@master

      - name: start localstack
        run: docker-compose up -d localstack

      - name: do pytest
        run: pytest

  assign-reviewer:
    runs-on: ubuntu-latest
    needs: unit-testing
    permissions:
      pull-requests: write
    steps:
      - name: Assign reviewers
        uses: monty16597/github-pr-reviewer-request-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.repository }}
          pr_number: ${{ github.event.number }}
          pr_reviewers: 'krutipatel15,monty16597'
          do_comment: true
          custom_comment: 'Please review this PR @krutipatel15'
